name: mvp
description: Flutter package to build applications using Model View Presenter (MVP) architecture.
version: 0.0.0
author: David Serrano Canales (svprdga)
homepage: https://github.com/svprdga/mvp

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
